LPD-59857 Temporary remove testing localized custom fields until bug causing a parsing error in the headless client when dealing with localized custom fields is resolved
Error:
java.lang.IllegalAccessException: class com.liferay.headless.admin.site.client.json.BaseJSONParser cannot access a member of class com.liferay.headless.admin.site.client.custom.field.CustomValue$CustomValueJSONParser with modifiers "private"