LPD-55438 WIP - Define Favicon through allOf and oneOf
buildRest fails with:

> Task :apps:headless:headless-admin-site:headless-admin-site-impl:buildREST FAILED
Aug 20, 2025 9:01:12 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
Java method "com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool.getDTOProperties(com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML, com.liferay.portal.tools.rest.builder.internal.yaml.openap
i.OpenAPIYAML, com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Schema, Map)" threw an exception when invoked on com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool object "com.liferay.portal.tools.re
st.builder.internal.freemarker.tool.FreeMarkerTool@3e92cdd1"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: properties = freeMarkerTool.getDTOPro...  [in template "com/liferay/portal/tools/rest/builder/dependencies/dto.ftl" at line 131, column 17]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:292)
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:264)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:66)
        at freemarker.core.MethodCall._eval(MethodCall.java:62)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.Assignment.accept(Assignment.java:134)
        at freemarker.core.Environment.visit(Environment.java:344)
        at freemarker.core.Environment.visit(Environment.java:350)
        at freemarker.core.Environment.visit(Environment.java:350)
        at freemarker.core.Environment.process(Environment.java:323)
        at freemarker.template.Template.process(Template.java:383)
        at com.liferay.portal.tools.rest.builder.internal.freemarker.FreeMarker.processTemplate(FreeMarker.java:53)
        at com.liferay.portal.tools.rest.builder.internal.freemarker.util.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:24)
        at com.liferay.portal.tools.rest.builder.RESTBuilder._createDTOFile(RESTBuilder.java:813)
        at com.liferay.portal.tools.rest.builder.RESTBuilder.build(RESTBuilder.java:288)
        at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:106)
Caused by: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "javaDataType" is null
        at com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.DTOOpenAPIParser._getPropertyType(DTOOpenAPIParser.java:262)
        at com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.DTOOpenAPIParser.getProperties(DTOOpenAPIParser.java:82)
        at com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool.getDTOProperties(FreeMarkerTool.java:348)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1634)
        at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
        at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62)
        ... 13 more

Exception in thread "main" java.lang.RuntimeException: Error generating REST API
Java method "com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool.getDTOProperties(com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML, com.liferay.portal.tools.rest.builder.internal.yaml.openap
i.OpenAPIYAML, com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Schema, Map)" threw an exception when invoked on com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool object "com.liferay.portal.tools.re
st.builder.internal.freemarker.tool.FreeMarkerTool@3e92cdd1"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: properties = freeMarkerTool.getDTOPro...  [in template "com/liferay/portal/tools/rest/builder/dependencies/dto.ftl" at line 131, column 17]
----
        at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:117)
Caused by: freemarker.core._TemplateModelException: Java method "com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool.getDTOProperties(com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML, com.li
feray.portal.tools.rest.builder.internal.yaml.openapi.OpenAPIYAML, com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Schema, Map)" threw an exception when invoked on com.liferay.portal.tools.rest.builder.internal.freemarker.too
l.FreeMarkerTool object "com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool@3e92cdd1"; see cause exception in the Java stack trace.